### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by kylecourounis** [destruc7i0n/buycraft-vanilla#3]
This isn't really an issue, but your instructions on how to set this up are very unclear. It lacks some information I would like, and it's not very step by step. I think I've done it right, but I'm not sure. Can you maybe make a video tutorial on how to do this or something?

Much appreciated!
- opum2

**Comment by destruc7i0n** [comment]
Can you tell me what info you are looking for?

**Comment by kylecourounis** [comment]
I don't really understand the instructions. That's all. Very unclear to me.

**Comment by kylecourounis** [comment]
I still want to know, but I'm not too worried about this now, as I switched to a different server jar.

**Comment by destruc7i0n** [comment]
I've updated the installation progress. Take a look and tell me what you think?

**Comment by fieu** [comment]
By the looks of things, you really cleaned up and made the instructions more friendly. Good on ya @destruc7i0n ! 👍 👍
![neomagazinroyale-neomagazin-applaus-xT9DPlOC5LEOMLknAs](https://camo.githubusercontent.com/7c2b24a32b2153fe4ec1d59ac6b1d347f0978fdf/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78543944506c4f43354c454f4d4c6b6e41732f67697068792e676966)
