### ISSUE TITLE
#error

### ISSUE THREAD

**Issue by DrexHD** [destruc7i0n/buycraft-vanilla#6]
I installed it and now get this error in the buycraft.log:

Error: Forbidden
error: Forever detected script exited with code: 1

Can you help, do you need more information?

**Comment by destruc7i0n** [comment]
Can you possibly provide the version of Node, OS etc?

**Comment by DrexHD** [comment]
Node: v4.4.7
OS: v8.9
What else do you want to know?

**Comment by destruc7i0n** [comment]
Are you on Ubuntu?
Also, can you try running `node index.js` and telling me what error you get?

**Comment by DrexHD** [comment]
I am running on Linux debian and the error i get is:
"Error: Forbidden"

**Comment by destruc7i0n** [comment]
Anything else? I'm sure you'll get more.

**Comment by DrexHD** [comment]
This is how it looks:
[Link](http://www.bilder-upload.eu/show.php?file=f466c8-1518587696.png)

**Comment by DrexHD** [comment]
Hello?

**Comment by destruc7i0n** [comment]
Apparently Buycraft removed "official" support for this in their API... 

Can you please comment out [lines 10-24](https://github.com/destruc7i0n/buycraft-vanilla/blob/master/index.js#L10-L24) and try it again?

**Comment by DrexHD** [comment]
Ok `node index.js` now does nt give any error, but the buycraftlog gives this error now: **error: Forever detected script exited with code: 0** ,it gave out this with the lines 10-24: 

**Error: Forbidden
error: Forever detected script exited with code: 1**

**Comment by destruc7i0n** [comment]
Apparently I forgot an integral aspect...

Replace what you commented out with
```
// make sure buycraft key works
client.information(function(err, r) {
  if(err) {
    console.log("[ERROR] " + err);
    process.exit(1);
  } else {            
    checkDue();
  }
});    
```

**Comment by DrexHD** [comment]
Now i get this error: `error: Forever detected script was killed by signal: SIGKILL`

**Comment by destruc7i0n** [comment]
What if you run with node?

**Comment by DrexHD** [comment]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:22556
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

**Comment by destruc7i0n** [comment]
Have you edited the config to match your server etc?

**Comment by DrexHD** [comment]
Ok its connected now, but it only passes one payement and then i need to restart it

**Comment by destruc7i0n** [comment]
Sorry for the late reply. Are you running it via the bash script?

**Comment by DrexHD** [comment]
Via a command including with ./ ... .sh i think

**Comment by destruc7i0n** [comment]
`./buycraft start`?
